# Список (каталог) пользователей
GET http://localhost:3333/api/users?location=Петроградская&trainingType=йога&levelTraining=новичок&limit=15&page=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6ItCY0LLQsNC90L7QsiDQmNCy0LDQvSIsImlhdCI6MTY4ODUzNTQ5NywiZXhwIjoxNjg4NTM2Mzk3fQ.LRfchx5TOKIRl9zWULxJY1Ul-SodmnJuI_fhjK1Eo84
###

#  Детальная информация о пользователе (Карточка пользователя)
GET http://localhost:3333/api/users/6497fd0eaaa5a02715264c9b HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgwNjE5NzIsImV4cCI6MTY4ODA2Mjg3Mn0.8oPS2Nb3vGsYSaMZ1jonr89rPc_dfc2ZtwT2Tni5BZ8
Content-Type: application/json
###

#  Редактирование информации о пользователе (тренера)
POST http://localhost:3333/api/users/edit HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgwNjE5NzIsImV4cCI6MTY4ODA2Mjg3Mn0.8oPS2Nb3vGsYSaMZ1jonr89rPc_dfc2ZtwT2Tni5BZ8
Content-Type: application/json

{
  "location": "Звёздная"
  }

###

#  Редактирование информации о пользователе
POST http://localhost:3333/api/users/edit HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4NjZmNmRhYzA1MmU4NjE1ODlmNTkiLCJlbWFpbCI6InVzZXJOZXcxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwidXNlck5hbWUiOiLQodGC0LXQv9Cw0L3QvtCyINCh0YLQtdC_0LDQvSIsImlhdCI6MTY4NzcwOTQ1NywiZXhwIjoxNjg3NzEwMzU3fQ.0Ar9QhhGOXmDfkzZa31eI_e64Ipgqx8JYOc8TVXPljQ
Content-Type: application/json

{
  "userName": "Иванов Иван",
  "sex": "male",
  "dateBirth": "2012-02-22",
  "role": "coach",
  "description": "Иванов Иван Иванович",
  "location": "Пионерская",
  "levelTraining": "профессионал",
  "trainingType": ["йога"],
  "trainingTime": "10-30 мин",
  "caloriesReset": 1200,
  "caloriesSpend": 1500,
  "isReady": true
  }

###

#  Список оповещений пользователя (последние 5)
GET http://localhost:3333/api/users/notify/show HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCf0LXRgtGA0L7QsiIsImlhdCI6MTY4ODMxNDM0NywiZXhwIjoxNjg4MzE1MjQ3fQ.a4dMtbmS8Hd3J8ukOSRvaizd-3iY7gO0lL_7502UAoM
Content-Type: application/json
###

#  Удаление оповещения по ИД
DELETE http://localhost:3333/api/users/notify/delete/64a19dadd522ea56f37d5ea6 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCf0LXRgtGA0L7QsiIsImlhdCI6MTY4ODMxMzI3NywiZXhwIjoxNjg4MzE0MTc3fQ.JX-hEkCardm3tGecNaKLumTPJa8ON4-jw3pt8fXE9_0
Content-Type: application/json
###
