# Список (каталог) пользователей
GET http://localhost:3333/api/users?location=Петроградская&trainingType=йога&levelTraining=новичок&limit=15&page=1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgxMjY2MDAsImV4cCI6MTY4ODEyNzUwMH0.ZkkmM5jFPkTUExdRyJTuiTJ42jGgfQNHhf7nCZGcIIU
###

#  Детальная информация о пользователе (Карточка пользователя)
GET http://localhost:3333/api/users/6497fd0eaaa5a02715264c9b HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgwNjE5NzIsImV4cCI6MTY4ODA2Mjg3Mn0.8oPS2Nb3vGsYSaMZ1jonr89rPc_dfc2ZtwT2Tni5BZ8
Content-Type: application/json
###

#  Редактирование информации о пользователе (тренера)
POST http://localhost:3333/api/users/edit HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgwNjE5NzIsImV4cCI6MTY4ODA2Mjg3Mn0.8oPS2Nb3vGsYSaMZ1jonr89rPc_dfc2ZtwT2Tni5BZ8
Content-Type: application/json

{
  "location": "Звёздная"
  }

###

#  Редактирование информации о пользователе
POST http://localhost:3333/api/users/edit HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4NjZmNmRhYzA1MmU4NjE1ODlmNTkiLCJlbWFpbCI6InVzZXJOZXcxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwidXNlck5hbWUiOiLQodGC0LXQv9Cw0L3QvtCyINCh0YLQtdC_0LDQvSIsImlhdCI6MTY4NzcwOTQ1NywiZXhwIjoxNjg3NzEwMzU3fQ.0Ar9QhhGOXmDfkzZa31eI_e64Ipgqx8JYOc8TVXPljQ
Content-Type: application/json

{
  "userName": "Иванов Иван",
  "sex": "male",
  "dateBirth": "2012-02-22",
  "role": "coach",
  "description": "Иванов Иван Иванович",
  "location": "Пионерская",
  "levelTraining": "профессионал",
  "trainingType": ["йога"],
  "trainingTime": "10-30 мин",
  "caloriesReset": 1200,
  "caloriesSpend": 1500,
  "isReady": true
  }

###

