# Каталог тренировок
GET http://localhost:4000/api/training/catalog?price=10,4000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgyODQ2OTUsImV4cCI6MTY4ODI4NTU5NX0.daln3RS4-pk_G2D0TRQPQXnxFeFPSMzELap36XdyTXI
###

# Добавить комментарий
POST http://localhost:4000/api/training/comments/create/649afd18e0be2c6e2c674fbe HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgyODQ2OTUsImV4cCI6MTY4ODI4NTU5NX0.daln3RS4-pk_G2D0TRQPQXnxFeFPSMzELap36XdyTXI
Content-Type: application/json

{
  "message": "tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt",
  "ratingTraining": 1
}
###


# Список комментариев
GET http://localhost:4000/api/training/comments/649afd18e0be2c6e2c674fbe HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgyODQ2OTUsImV4cCI6MTY4ODI4NTU5NX0.daln3RS4-pk_G2D0TRQPQXnxFeFPSMzELap36XdyTXI
###
