#  Добавить друга
POST http://localhost:4000/api/user/friends/add/649da3764f4fc537d512a65e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgxNDM1MzQsImV4cCI6MTY4ODE0NDQzNH0.tHG2JjWjgOZ3ShsqhuH8F73RCAM4QNOWDtICzqkKuYY
Content-Type: application/json
###

#  Удалить пользователя из друзей
POST http://localhost:4000/api/user/friends/delete/649da3764f4fc537d512a65e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgxNDM1MzQsImV4cCI6MTY4ODE0NDQzNH0.tHG2JjWjgOZ3ShsqhuH8F73RCAM4QNOWDtICzqkKuYY
Content-Type: application/json
###

#  Список друзей пользователя
GET http://localhost:4000/api/user/friends/show HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgxNDM1MzQsImV4cCI6MTY4ODE0NDQzNH0.tHG2JjWjgOZ3ShsqhuH8F73RCAM4QNOWDtICzqkKuYY
Content-Type: application/json
###

# Создание заказа
POST http://localhost:4000/api/user/orders/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDlkYTM3NjRmNGZjNTM3ZDUxMmE2NWUiLCJlbWFpbCI6InVzZXJOZXczQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6ItCY0LLQsNC90L7QsiDQmNCy0LDQvSIsImlhdCI6MTY4ODIyOTI4NiwiZXhwIjoxNjg4MjMwMTg2fQ.o9m2YWVIPfGc2CFyQqIoXYQCGtAc7TJhTzRa__SW9SM
Content-Type: application/json

{
  "trainingId": "649afe8c1b6c87810dbb07bf",
  "trainingCount": 2,
  "paymentOption": "visa"
}
###

# Списание тренировки
POST http://localhost:4000/api/user/orders/reduce/64a0676fd318a9cca4845490 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgyMzY3NTIsImV4cCI6MTY4ODIzNzY1Mn0.9Kn4XXbT8FIqrt6xV0XcLL7zeI21V_3dCRsoEpbWiRE
Content-Type: application/json
###

# Баланс пользователя
GET http://localhost:4000/api/user/orders?sortPrice=desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgyMzY3NTIsImV4cCI6MTY4ODIzNzY1Mn0.9Kn4XXbT8FIqrt6xV0XcLL7zeI21V_3dCRsoEpbWiRE
###

# Удаление заказа
DELETE http://localhost:4000/api/user/orders/delete/64a0673bd318a9cca4845484 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgyMzY3NTIsImV4cCI6MTY4ODIzNzY1Mn0.9Kn4XXbT8FIqrt6xV0XcLL7zeI21V_3dCRsoEpbWiRE
Content-Type: application/json
###

# Подписка на получение уведомлений по email на появление новых тренировок определённого тренера
POST http://localhost:4000/api/user/subscription/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgyMjQ3OTIsImV4cCI6MTY4ODIyNTY5Mn0.79BHsZhfwKpB10PaT0cX0oRtuP5dQ_GHPCq9DgLhEiI
Content-Type: application/json

{
  "coachId": "6497fd0eaaa5a02715264c9b"
}

###

# Отмена подписки на других пользователей.
DELETE  http://localhost:4000/api/user/subscription/delete HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgyMjQ3OTIsImV4cCI6MTY4ODIyNTY5Mn0.79BHsZhfwKpB10PaT0cX0oRtuP5dQ_GHPCq9DgLhEiI
Content-Type: application/json

{
  "coachId": "6497fd0eaaa5a02715264c9b"
}
###
# Рассылка почтовых уведомлений на email о новых тренировках
GET http://localhost:4000/api/user/notify/newtraining HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgyMjQ3OTIsImV4cCI6MTY4ODIyNTY5Mn0.79BHsZhfwKpB10PaT0cX0oRtuP5dQ_GHPCq9DgLhEiI
Content-Type: application/json

###

