# Создание тренировки
POST http://localhost:4000/api/coach/training/create HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4NjZmNmRhYzA1MmU4NjE1ODlmNTkiLCJlbWFpbCI6InVzZXJOZXcxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwidXNlck5hbWUiOiLQodGC0LXQv9Cw0L3QvtCyINCh0YLQtdC_0LDQvSIsImlhdCI6MTY4ODEyMzYxNSwiZXhwIjoxNjg4MTI0NTE1fQ.BkIFm9F2dVv8xedjiUutz6C29A3pw16MtO6-fvc53jE
Content-Type: application/json

{
  "nameTraining": "Тренировка 55",
  "levelTraining": "любитель",
  "trainingType": "йога",
  "trainingTime": "10-30 мин",
  "price": 2000,
  "caloriesReset": 3000,
  "descriptionTraining": "Тренировка 5",
  "sex": "male",
  "isSpecialOffer": true
}
###
# Редактирование  тренировки
POST http://localhost:4000/api/coach/training/edit/649afd18e0be2c6e2c674fbe HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCf0LXRgtGA0L7QsiIsImlhdCI6MTY4ODEzOTkzMiwiZXhwIjoxNjg4MTQwODMyfQ.uCu4bAJct68Ml6ItvTyvNmNm0R_NFtnV29Z5WDWNTTI
Content-Type: application/json

{
  "price": 3000
}
###
# Детальная информация о тренировке
GET http://localhost:4000/api/coach/training/649afe8c1b6c87810dbb07bf HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4NjZmNmRhYzA1MmU4NjE1ODlmNTkiLCJlbWFpbCI6InVzZXJOZXcxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwidXNlck5hbWUiOiLQodGC0LXQv9Cw0L3QvtCyINCh0YLQtdC_0LDQvSIsImlhdCI6MTY4ODEyMzYxNSwiZXhwIjoxNjg4MTI0NTE1fQ.BkIFm9F2dVv8xedjiUutz6C29A3pw16MtO6-fvc53jE
Content-Type: application/json
###

# Список тренировок
GET http://localhost:4000/api/coach/training/show/list?price=10,3000 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDlkYTM1NDRmNGZjNTM3ZDUxMmE2NTYiLCJlbWFpbCI6InVzZXJOZXcyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LLQsCDQmNGA0LjQvdCwIiwiaWF0IjoxNjg4MTQwNDc0LCJleHAiOjE2ODgxNDEzNzR9.YD-oKDWgKP1zjxDsSJG96SOft0HloT8qSRpuiWabJRs
###

# Список заказов для тренера
GET http://localhost:4000/api/coach/orders?sortPrice=desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDlkYTM1NDRmNGZjNTM3ZDUxMmE2NTYiLCJlbWFpbCI6InVzZXJOZXcyQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LLQsCDQmNGA0LjQvdCwIiwiaWF0IjoxNjg4MTQwOTA0LCJleHAiOjE2ODgxNDE4MDR9.2Fwh5e_RGWd3K3uqXSn7_dPzADz2srHnENX2Cbj8sRI
###

#  Список друзей тренера
GET http://localhost:4000/api/coach/friends/show HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCf0LXRgtGA0L7QsiIsImlhdCI6MTY4ODE0MDk5NSwiZXhwIjoxNjg4MTQxODk1fQ.rQiiROAJ-uBXzDXvGq0haJISYNNqMmXBQbK-NiKFHuE
Content-Type: application/json
###

#  Удалиться из списка друзей
POST http://localhost:4000/api/coach/friends/delete/649809159b59277aa0c615a7 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCf0LXRgtGA0L7QsiIsImlhdCI6MTY4ODE0MzcwMiwiZXhwIjoxNjg4MTQ0NjAyfQ.lbzrCOYAXBooXVV3rIpAUC0s5jW-mg4fa5kEWKujTcc
Content-Type: application/json
###
