# Создание тренировки
POST http://localhost:3334/api/training/create HTTP/1.1
Content-Type: application/json

{
  "nameTraining": "Тренировка йога",
  "levelTraining": "любитель",
  "trainingType": "йога",
  "trainingTime": "10-30 мин",
  "price": 2000,
  "caloriesReset": 3000,
  "descriptionTraining": "йога просто супер",
  "sex": "male",
  "isSpecialOffer": true,
  "coachId": "649866f6dac052e861589f59"
}
###
# Редактирование  тренировки
POST http://localhost:3334/api/training/edit/649afd18e0be2c6e2c674fbe HTTP/1.1
Content-Type: application/json

{
  "levelTraining": "новичок"
}
###
# Детальная информация о тренировке
GET http://localhost:3334/api/training/649afd18e0be2c6e2c674fbe HTTP/1.1
Content-Type: application/json
###

# Список тренировок тренера
GET http://localhost:3334/api/training/show/list?sortDate=desc&limit=45 HTTP/1.1
Content-Type: application/json

{
  "coachId": "6497fd0eaaa5a02715264c9b"
}
###

# Каталог тренировок
GET http://localhost:3334/api/training/show/catalog?trainingType=йога,бокс&sortDate=desc HTTP/1.1
###
# Создание заказа
POST http://localhost:3334/api/orders/create HTTP/1.1
Content-Type: application/json

{
  "userId": "649da3764f4fc537d512a65e",
  "trainingId": "649afeb71b6c87810dbb07c2",
  "trainingCount": 8,
  "paymentOption": "visa"
}
###

# Списание тренировки из заказа
POST http://localhost:3334/api/orders/reduce/64a06743d318a9cca4845488 HTTP/1.1
Content-Type: application/json
###

# Удаление заказа
DELETE http://localhost:3334/api/orders/delete/649afd18e0be2c6e2c674fbe HTTP/1.1
Content-Type: application/json
###


# @name login
POST http://localhost:3333/api/auth/login HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "email": "user1@notfound.local",
  "password": "1234567"
}
###
@authToken = {{login.response.body.accessToken}}
# Список заказов для тренера
GET http://localhost:3334/api/orders/show/list?sortDate=1 HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "coachId": "6497fd0eaaa5a02715264c9b"a
}
###

# Список заказов для пользователя (баланс пользователя)
GET http://localhost:3334/api/orders/show/list/user HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "userId": "649809159b59277aa0c615a7"
}
###


# Просмотр заказа
GET http://localhost:3334/api/orders/649afd18e0be2c6e2c674fbe HTTP/1.1
Authorization: Bearer {{authToken}}

###
# Создание заявки
POST http://localhost:3334/api/request/create HTTP/1.1
Content-Type: application/json

{
  "initiatorId": "649809159b59277aa0c615a7",
  "userId": "649da3764f4fc537d512a65e",
  "statusRequest": "на рассмотрении",
  "typeRequest": "совместная тренировка"
}
###

# Изменений статуса заявки
POST http://localhost:3334/api/request/update/64a3093fd7241e966c55625d HTTP/1.1
Content-Type: application/json

{
  "statusRequest": "принят"
}
###

# Удаление заявки
DELETE http://localhost:3334/api/request/delete/64a3093fd7241e966c55625d HTTP/1.1
Content-Type: application/json
###
# Создание отзыва к тренировке
POST http://localhost:3334/api/comment/create/649afd18e0be2c6e2c674fbe HTTP/1.1
Content-Type: application/json

{
  "message": "tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt",
  "ratingTraining": 1,
  "userId": "649809159b59277aa0c615a7"
}

###

# Список комментариев к тренировке
GET http://localhost:3334/api/comment/64a406e9c4d605ea3e822df6?limit=5&page=1&sortDate=desc HTTP/1.1
Content-Type: application/json
###


