# Добавить друга
POST http://localhost:3333/api/friends/add/6497fd0eaaa5a02715264c9b HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6ItCY0LLQsNC90L7QsiDQmNCy0LDQvSIsImlhdCI6MTY4ODUzNjkyMywiZXhwIjoxNjg4NTM3ODIzfQ.nCu_o0USTxy8OUW1P5x8wRYyRVbLQsb2HTDKBHEdDQk

###

# Список друзей пользователя
GET http://localhost:3333/api/friends/user?sortDate=desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXIxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6InVzZXIiLCJ1c2VyTmFtZSI6ItCY0LLQsNC90L7QsiDQmNCy0LDQvSIsImlhdCI6MTY4ODUzNjkyMywiZXhwIjoxNjg4NTM3ODIzfQ.nCu_o0USTxy8OUW1P5x8wRYyRVbLQsb2HTDKBHEdDQk
###



#  Список друзей тренера
GET http://localhost:3333/api/friends/coach?sortDate=desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6ImNvYWNoMUBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJjb2FjaCIsInVzZXJOYW1lIjoi0J_QtdGC0YDQvtCyINCf0LXRgtGAIiwiaWF0IjoxNjg4NTM2OTYyLCJleHAiOjE2ODg1Mzc4NjJ9.X9PgOLGBruFw7jCA8pncOkZrnG_NSfpZNyOqP52bfyQ
Content-Type: application/json
###

#  Удаление из списка друзей для тренера
POST http://localhost:3333/api/friends/delete/coach/649da3764f4fc537d512a65e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCf0LXRgtGA0L7QsiIsImlhdCI6MTY4ODE0MzcwMiwiZXhwIjoxNjg4MTQ0NjAyfQ.lbzrCOYAXBooXVV3rIpAUC0s5jW-mg4fa5kEWKujTcc
Content-Type: application/json

###

#  Удаление из списка друзей для пользователя
POST http://localhost:3333/api/friends/delete/649da3764f4fc537d512a65e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgxNDI1ODEsImV4cCI6MTY4ODE0MzQ4MX0.TIkD_fqKSqn84ijFuxh97ofXpWcb7zYr15XTWOKVE_U
Content-Type: application/json

###
