# Добавить друга
POST http://localhost:3333/api/friends/add/6497fd0eaaa5a02715264c9b HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4NjZmNmRhYzA1MmU4NjE1ODlmNTkiLCJlbWFpbCI6InVzZXJOZXcxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwidXNlck5hbWUiOiLQodGC0LXQv9Cw0L3QvtCyINCh0YLQtdC_0LDQvSIsImlhdCI6MTY4ODMxMzI1MSwiZXhwIjoxNjg4MzE0MTUxfQ.AH4jIWOiOfo59rc-ZXEL6lmu3nz-Oe8s1by88Ko1wy4

###

# Список друзей пользователя
GET http://localhost:3333/api/friends/user HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODc5Njg5NjQsImV4cCI6MTY4Nzk2OTg2NH0.GxQyXdf7-9S_8YmKR6PywZ5v036MrtlfkSHWyH2ZGaI
###



#  Список друзей тренера
GET http://localhost:3333/api/friends/coach HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCf0LXRgtGA0L7QsiIsImlhdCI6MTY4ODE0MDk5NSwiZXhwIjoxNjg4MTQxODk1fQ.rQiiROAJ-uBXzDXvGq0haJISYNNqMmXBQbK-NiKFHuE
Content-Type: application/json
###

#  Удаление из списка друзей для тренера
POST http://localhost:3333/api/friends/delete/coach/649da3764f4fc537d512a65e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCf0LXRgtGA0L7QsiIsImlhdCI6MTY4ODE0MzcwMiwiZXhwIjoxNjg4MTQ0NjAyfQ.lbzrCOYAXBooXVV3rIpAUC0s5jW-mg4fa5kEWKujTcc
Content-Type: application/json

###

#  Удаление из списка друзей для пользователя
POST http://localhost:3333/api/friends/delete/649da3764f4fc537d512a65e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgxNDI1ODEsImV4cCI6MTY4ODE0MzQ4MX0.TIkD_fqKSqn84ijFuxh97ofXpWcb7zYr15XTWOKVE_U
Content-Type: application/json

###
