# Регистрация новых пользователей. Тренер
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "userNew1@notfound.local",
  "userName": "Степанов Степан",
  "password": "1234567",
  "sex": "male",
  "dateBirth": "2012-02-22",
  "role": "coach",
  "description": "Степанов Степан Иванович",
  "location": "Удельная",
  "levelTraining": "любитель",
  "trainingType": ["йога", "аэробика"],
  "successCoach": "Ооочень крутой тренер",
  "isPersonal": true
  }

###

# Регистрация новых пользователей. Пользователь
POST http://localhost:3333/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email": "userNew10@notfound.local",
  "userName": "Иванов Иван",
  "password": "1234567",
  "sex": "male",
  "dateBirth": "2012-02-22",
  "role": "user",
  "description": "Иванов Иван Иванович",
  "location": "Пионерская",
  "levelTraining": "новичок",
  "trainingType": ["йога"],
  "trainingTime": "10-30 мин",
  "caloriesReset": 1200,
  "caloriesSpend": 1500,
  "isReady": true
  }

###

# Авторизация
POST http://localhost:3333/api/auth/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCf0LXRgtGA0L7QsiIsImlhdCI6MTY4ODA1ODQ1NSwiZXhwIjoxNjg4MDU5MzU1fQ.cM2JyECVlHCkUAdrLawgh0c8N00LBuJ8rR3rDqbCj6U
Content-Type: application/json

{
  "email": "userNew3@notfound.local",
  "password": "1234567"
}
###

# Проверка токена
POST http://localhost:3333/api/auth/check HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4NjZmNmRhYzA1MmU4NjE1ODlmNTkiLCJlbWFpbCI6InVzZXJOZXcxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwidXNlck5hbWUiOiLQodGC0LXQv9Cw0L3QvtCyINCh0YLQtdC_0LDQvSIsImlhdCI6MTY4NzcwOTc0NiwiZXhwIjoxNjg3NzEwNjQ2fQ.oGAqoGnOzH4OCFao2e-4A-xLaO15Gc8VRSI-u_GBOcg
###

# Проверка токена
POST http://localhost:3333/api/auth/isauth HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4NjZmNmRhYzA1MmU4NjE1ODlmNTkiLCJlbWFpbCI6InVzZXJOZXcxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwidXNlck5hbWUiOiLQodGC0LXQv9Cw0L3QvtCyINCh0YLQtdC_0LDQvSIsImlhdCI6MTY4NzcwOTc0NiwiZXhwIjoxNjg3NzEwNjQ2fQ.oGAqoGnOzH4OCFao2e-4A-xLaO15Gc8VRSI-u_GBOcg
###

# Обновление токенов
POST http://localhost:3333/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4NjZmNmRhYzA1MmU4NjE1ODlmNTkiLCJlbWFpbCI6InVzZXJOZXcxQG5vdGZvdW5kLmxvY2FsIiwicm9sZSI6ImNvYWNoIiwidXNlck5hbWUiOiLQodGC0LXQv9Cw0L3QvtCyINCh0YLQtdC_0LDQvSIsInRva2VuSWQiOiJhNzI5MjY1OS1mNDZjLTQwNzYtYjBjZi04YWE5OTY3MDY1NjIiLCJpYXQiOjE2ODc3MTA3MzEsImV4cCI6MTY4ODMxNTUzMX0.Ee79tjZpLOhPVaIu2Sm1oqtW38OI8VigQkzoY1qqAb0

###
# Удаление refresh token
POST http://localhost:3333/api/auth/refresh/delete HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgyMDUyMzEsImV4cCI6MTY4ODIwNjEzMX0.2p9twucaBil0HDs1ogl2iJcDN0XCSRBYQx0oUCGnqAg

###
# Рассылка почтовых уведомлений на email о появлении новых тренировок.
GET http://localhost:3333/api/auth/notify/newtraining HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk4MDkxNTliNTkyNzdhYTBjNjE1YTciLCJlbWFpbCI6InVzZXJOZXcxMEBub3Rmb3VuZC5sb2NhbCIsInJvbGUiOiJ1c2VyIiwidXNlck5hbWUiOiLQmNCy0LDQvdC-0LIg0JjQstCw0L0iLCJpYXQiOjE2ODgyMjQxOTcsImV4cCI6MTY4ODIyNTA5N30.aEyxfq_62505ZHYyhBvQU6hZCF9LDlL_XU_rfEQPTMg
Content-Type: application/json

###
