# Создание тренировки
POST http://localhost:3334/api/training/create HTTP/1.1
Content-Type: application/json

{
  "nameTraining": "Тренировка йога",
  "levelTraining": "любитель",
  "trainingType": "йога",
  "trainingTime": "10-30 мин",
  "price": 2000,
  "caloriesReset": 3000,
  "descriptionTraining": "йога просто супер",
  "sex": "male",
  "isSpecialOffer": true,
  "coachId": "649866f6dac052e861589f59"
}
###
# Редактирование  тренировки
POST http://localhost:3334/api/training/edit/649afd18e0be2c6e2c674fbe HTTP/1.1
Content-Type: application/json

{
  "levelTraining": "новичок"
}
###
# Детальная информация о тренировке
GET http://localhost:3334/api/training/649afd18e0be2c6e2c674fbe HTTP/1.1
Content-Type: application/json
###

# Список тренировок тренера
GET http://localhost:3334/api/training/show/list?sortDate=desc&limit=45 HTTP/1.1
Content-Type: application/json

{
  "coachId": "6497fd0eaaa5a02715264c9b"
}
###

# Каталог тренировок
GET http://localhost:3334/api/training/show/catalog?trainingType=йога,бокс&sortDate=desc HTTP/1.1
###
