# Создание заказа
POST http://localhost:3334/api/orders/create/649809159b59277aa0c615a7 HTTP/1.1
Content-Type: application/json

{
  "trainingId": "649afe8c1b6c87810dbb07bf",
  "trainingCount": 2,
  "paymentOption": "visa"
}
###

# Удаление заказа
GET http://localhost:3334/api/orders/delete/649afd18e0be2c6e2c674fbe HTTP/1.1
Content-Type: application/json
###

# Список заказов для тренера
GET http://localhost:3334/api/orders/show/list?sortPrice=desc HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NDk3ZmQwZWFhYTVhMDI3MTUyNjRjOWIiLCJlbWFpbCI6InVzZXJOZXdAbm90Zm91bmQubG9jYWwiLCJyb2xlIjoiY29hY2giLCJ1c2VyTmFtZSI6ItCf0LXRgtGA0L7QsiIsImlhdCI6MTY4ODE0MDYzNCwiZXhwIjoxNjg4MTQxNTM0fQ.qxPOyMtj8dyMIXMRD4R8LmkCeGNmemEo0X8HpDKxwVQ

###

