# Создание заказа
POST http://localhost:3334/api/orders/create/649809159b59277aa0c615a7 HTTP/1.1
Content-Type: application/json

{
  "trainingId": "649afe8c1b6c87810dbb07bf",
  "trainingCount": 2,
  "paymentOption": "visa"
}
###

# Удаление заказа
GET http://localhost:3334/api/orders/delete/649afd18e0be2c6e2c674fbe HTTP/1.1
Content-Type: application/json
###

# Список заказов для тренера
GET http://localhost:3334/api/orders/list/6497fd0eaaa5a02715264c9b?sortPrice=desc HTTP/1.1
###

